sudo: required
dist: trusty

# Do not choose a language; we provide our own build tools.
language: generic

matrix:
  include:
    - env: STACK_YAML=stack.yaml COVERAGE=1 SHC_GHCVER=8.0.1
      compiler: ": #GHC 8.4.3"
    - env: STACK_YAML=stack.yaml
      compiler: ": #GHC 8.4.3"
      os: osx
    - env: STACK_YAML=stack-ghc-8.2.yaml
      compiler: ": #GHC 8.2.2"
    - env: STACK_YAML=stack-ghc-8.0.yaml
      compiler: ": #GHC 8.0.2"
    - env: STACK_YAML=stack-ghc-7.10.yaml
      compiler: ": #GHC 7.10.3"
    - env: STACK_YAML=stack-ghc-7.8.yaml
      compiler: ": #GHC 7.8.4"

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

before_install:
# Download and unpack the stack executable
- mkdir -p $HOME/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- |
  if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    travis_retry curl -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 -C ~/.local/bin '*/stack'
  else
    travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi

install:
# Build dependencies
- if [ -n "$COVERAGE" ]; then FLAGS="$FLAGS --coverage"; fi
- stack --jobs 2 --no-terminal --install-ghc build --test --bench --only-dependencies $FLAGS

script:
# Build the package, its tests, and its docs and run the tests
- stack --jobs 2 --no-terminal test --bench --no-run-benchmarks $FLAGS

after_script:
- |
  if [ -n "$COVERAGE" ]; then
    travis_retry curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.4.0/shc-linux-x64-$SHC_GHCVER.tar.bz2 | tar -xj
    ./shc bytestring-encoding bytestring-encoding-test
  fi
