platform:
- x64

environment:
  global:
    STACK_ROOT: "c:\\sr"

cache:
- "c:\\sr" # stack root, short paths == less problems

install:
- curl -ostack.zip -L --insecure http://www.stackage.org/stack/windows-x86_64
- 7z x stack.zip stack.exe
- stack setup > nul

build_script:
- echo "" | stack --no-terminal build --test --no-run-tests

test_script:
- echo "" | stack --no-terminal test
